import { Translations, Service, Project } from './types';

export const translations: Translations = {
    en: {
        nav_logo: "Mohammed Ibrahim Abdullah",
        nav_about: "About Me",
        nav_services: "Services",
        nav_projects: "Projects",
        nav_contact: "Contact Me",
        nav_community: "Community",
        nav_admin: "Admin Panel",
        nav_login: "Login",
        nav_signup: "Sign Up",
        nav_logout: "Logout",
        hero_title: "Mohammed Ibrahim Abdullah",
        hero_subtitle: "Automation & AI Integration Specialist",
        hero_description: "I build intelligent systems and custom solutions that connect your ideas to the digital world, using advanced tools like n8n and custom UIs to achieve maximum efficiency.",
        about_section_title: "Who I Am",
        about_heading: "Building Bridges Between Ideas & Smart Systems",
        about_p1: "My passion lies in transforming complex processes into seamless, automated systems. With expertise in building advanced n8n workflows, developing interactive Telegram bots, and designing custom user interfaces, I deliver innovative solutions for businesses and individuals.",
        about_p2: "I combine my 'vibe coding' skills—programming with a flexible logic without being tied to a specific language—and my past experience in game development (Godot/GDScript) to create solutions that are not only effective but also intelligent and enjoyable to interact with.",
        about_cert_btn_text: "Download Certificates PDF",
        about_credly_btn: "View Credly Badges",
        about_udacity_btn: "Udacity Certificate",
        services_title: "Services I Offer",
        projects_title: "Featured Projects",
        contact_title: "Get in Touch",
        contact_subtitle: "Have a project idea? Or want to discuss automation solutions for your business? Fill out the form below, and I'll get back to you soon.",
        contact_form_service: "Select a Service",
        contact_form_name: "Full Name",
        contact_form_email: "Email Address",
        contact_form_phone: "Phone Number",
        contact_form_contact_method: "Preferred Contact Method",
        contact_phone_call: "Phone Call",
        contact_whatsapp: "WhatsApp",
        contact_zoom: "Zoom",
        contact_discord: "Discord",
        contact_form_message: "Your message or project details",
        contact_form_submit: "Send Request",
        form_success: "Your request has been received successfully! I will contact you soon.",
        form_error: "An error occurred while sending. Please try again or contact me directly.",
        form_sending: "Sending...",
        footer_copyright: "© 2024 Mohammed Ibrahim Abdullah. All rights reserved.",
        filter_all: "All",
        filter_websites: "Websites",
        filter_n8n: "n8n Workflows",
        project_link_text: "View Project",
        modal_login_title: "Login",
        modal_signup_title: "Create Account",
        modal_password: "Password",
        modal_login_btn: "Login",
        modal_signup_btn: "Sign Up",
        modal_switch_to_signup_text: "Don't have an account?",
        modal_switch_to_signup_link: "Sign Up",
        modal_switch_to_login_text: "Already have an account?",
        modal_switch_to_login_link: "Login",
        community_title: "Community Hub",
        community_subtitle: "Share your projects, discover new courses, and collaborate with others.",
        community_create_post: "Create Post",
        community_filter_projects: "Projects",
        community_filter_courses: "Courses & Workshops",
        community_enroll: "Enroll",
        community_purchase: "Purchase for",
        community_free: "Free",
        community_by: "By",
        community_view_details: "View Details",
        create_post_title: "Create a New Post",
        create_post_type: "Post Type",
        create_post_type_project: "Project",
        create_post_type_course: "Course / Workshop",
        create_post_title_label: "Title",
        create_post_desc_label: "Description",
        create_post_is_paid: "Is this a paid item?",
        create_post_price_label: "Price (USD)",
        create_post_submit: "Submit for Review",
        post_created_success: "Post submitted for review successfully!",
        post_created_error: "Error submitting post. Please try again.",
        admin_title: "Admin Panel",
        admin_subtitle: "Manage community submissions.",
        admin_approve: "Approve",
        admin_approved: "Approved",
        admin_pending: "Pending Approval",
        admin_no_posts: "No pending posts to review.",
        admin_status: "Status",
        admin_author: "Author",
        admin_post_title: "Title",
        admin_price: "Price",
        admin_actions: "Actions",
        // Chatbot translations
        bot_welcome: "Welcome! I'm Mabda Bot. How can I guide you today? 🤖",
        bot_option_services: "Explore Services",
        bot_option_projects: "Show me his best work",
        bot_option_hire: "I want to hire him!",
        bot_option_consultation: "Get AI Consultation",
        bot_proactive_prompt: "Psst! Looking for smart automation? Let me guide you.",
        bot_proactive_cta: "Let's Talk",
        bot_back: "Back",
        bot_back_to_services: "See other services",
        bot_contact_about_this: "Contact about this",
        bot_request_this_service: "Request This Service",
        bot_request_service_title: "Request This Service",
        bot_request_service_prompt: "Great choice! Please provide your details below to get started.",
        bot_request_service_name_placeholder: "Your Name",
        bot_request_service_email_placeholder: "Your Email",
        bot_request_service_phone_placeholder: "Your Phone (Optional)",
        bot_request_service_message_placeholder: "Briefly describe your project or idea...",
        bot_request_service_submit: "Send Request",
        bot_request_success: "Thanks! Your request has been sent. We'll be in touch soon.",
        bot_error_key: "Chatbot is temporarily unavailable (API key missing).",
        bot_error_api: "Sorry, I'm having trouble connecting right now. Please try again later.",
        bot_consultation_title: "AI Project Consultation",
        bot_consultation_prompt: "Describe your business challenge or the process you want to automate. The more detail, the better the proposal!",
        bot_consultation_submit: "Generate Proposal",
        bot_consultation_analyzing: "Analyzing your problem...",
        bot_proposal_title: "Here is Your AI-Powered Proposal",
        bot_proposal_problem: "Problem Analysis",
        bot_proposal_solution: "Proposed Solution",
        bot_proposal_services: "Recommended Services",
        bot_discuss_proposal: "Discuss This Proposal",
        bot_brainstorm_idea: "Let's brainstorm an idea",
        bot_brainstorm_prompt: "What's on your mind? Describe your vision or problem.",
        bot_brainstorm_submit: "Get Feedback",
        bot_brainstorm_analyzing: "Thinking...",
        bot_brainstorm_response_title: "Here's a thought...",
        bot_discuss_idea: "Discuss This Idea",
    },
    ar: {
        nav_logo: "محمد ابراهيم عبدالله",
        nav_about: "من أنا",
        nav_services: "خدماتي",
        nav_projects: "المشاريع",
        nav_contact: "تواصل معي",
        nav_community: "المجتمع",
        nav_admin: "لوحة التحكم",
        nav_login: "تسجيل الدخول",
        nav_signup: "إنشاء حساب",
        nav_logout: "تسجيل الخروج",
        hero_title: "محمد ابراهيم عبدالله",
        hero_subtitle: "متخصص في أتمتة العمليات وتكامل الذكاء الاصطناعي",
        hero_description: "أقوم ببناء أنظمة ذكية وحلول مخصصة تربط بين أفكارك والواقع الرقمي، باستخدام أدوات متقدمة مثل n8n وواجهات برمجية مخصصة لتحقيق أقصى كفاءة.",
        about_section_title: "من أنا",
        about_heading: "بناء الجسور بين الأفكار والأنظمة الذكية",
        about_p1: "شغفي يكمن في تحويل العمليات المعقدة إلى أنظمة تلقائية وسلسة. بخبرة في بناء ووركفلوهات متقدمة باستخدام n8n، تطوير بوتات تليجرام تفاعلية، وتصميم واجهات مستخدم مخصصة، أقدم حلولاً مبتكرة للشركات والأفراد.",
        about_p2: "أجمع بين مهاراتي في \"vibe coding\" — حيث أبرمج بمنطق مرن دون التقيد بلغة معينة — وخبرتي السابقة في صناعة الألعاب (Godot/GDScript)، لإنشاء حلول ليست فقط فعالة، بل أيضًا ذكية وممتعة في التفاعل معها.",
        about_cert_btn_text: "تحميل ملف الشهادات",
        about_credly_btn: "عرض شارات Credly",
        about_udacity_btn: "شهادة يوداسيتي",
        services_title: "الخدمات التي أقدمها",
        projects_title: "أبرز المشاريع",
        contact_title: "تواصل معي",
        contact_subtitle: "هل لديك فكرة مشروع؟ أو ترغب في مناقشة حلول أتمتة لعملك؟ املأ النموذج أدناه وسأتواصل معك قريبًا.",
        contact_form_service: "اختر الخدمة المطلوبة",
        contact_form_name: "الاسم الكامل",
        contact_form_email: "البريد الإلكتروني",
        contact_form_phone: "رقم الهاتف",
        contact_form_contact_method: "طريقة التواصل المفضلة",
        contact_phone_call: "مكالمة هاتفية",
        contact_whatsapp: "واتساب",
        contact_zoom: "زووم",
        contact_discord: "ديسكورد",
        contact_form_message: "رسالتك أو تفاصيل مشروعك",
        contact_form_submit: "إرسال الطلب",
        form_success: "تم استلام طلبك بنجاح! سيتم التواصل معك قريبًا.",
        form_error: "حدث خطأ أثناء الإرسال. يرجى المحاولة مرة أخرى أو التواصل معي مباشرة.",
        form_sending: "...جاري الإرسال",
        footer_copyright: "© 2024 محمد ابراهيم عبدالله. جميع الحقوق محفوظة.",
        filter_all: "الكل",
        filter_websites: "مواقع",
        filter_n8n: "n8n Workflows",
        project_link_text: "شاهد المشروع",
        modal_login_title: "تسجيل الدخول",
        modal_signup_title: "إنشاء حساب",
        modal_password: "كلمة المرور",
        modal_login_btn: "تسجيل الدخول",
        modal_signup_btn: "إنشاء حساب",
        modal_switch_to_signup_text: "ليس لديك حساب؟",
        modal_switch_to_signup_link: "أنشئ حسابًا",
        modal_switch_to_login_text: "لديك حساب بالفعل؟",
        modal_switch_to_login_link: "سجل الدخول",
        community_title: "مركز المجتمع",
        community_subtitle: "شارك مشاريعك، اكتشف دورات جديدة، وتعاون مع الآخرين.",
        community_create_post: "أنشئ منشوراً",
        community_filter_projects: "مشاريع",
        community_filter_courses: "دورات وورش عمل",
        community_enroll: "تسجيل",
        community_purchase: "شراء مقابل",
        community_free: "مجاني",
        community_by: "بواسطة",
        community_view_details: "عرض التفاصيل",
        create_post_title: "إنشاء منشور جديد",
        create_post_type: "نوع المنشور",
        create_post_type_project: "مشروع",
        create_post_type_course: "دورة / ورشة عمل",
        create_post_title_label: "العنوان",
        create_post_desc_label: "الوصف",
        create_post_is_paid: "هل هذا عنصر مدفوع؟",
        create_post_price_label: "السعر (بالدولار)",
        create_post_submit: "إرسال للمراجعة",
        post_created_success: "تم إرسال المنشور للمراجعة بنجاح!",
        post_created_error: "خطأ في إرسال المنشور. يرجى المحاولة مرة أخرى.",
        admin_title: "لوحة التحكم",
        admin_subtitle: "إدارة منشورات المجتمع.",
        admin_approve: "موافقة",
        admin_approved: "تمت الموافقة",
        admin_pending: "في انتظار الموافقة",
        admin_no_posts: "لا توجد منشورات معلقة للمراجعة.",
        admin_status: "الحالة",
        admin_author: "المؤلف",
        admin_post_title: "العنوان",
        admin_price: "السعر",
        admin_actions: "الإجراءات",
        // Chatbot translations
        bot_welcome: "أهلاً بك! أنا مبدع بوت. كيف يمكنني إرشادك اليوم؟ 🤖",
        bot_option_services: "استكشف الخدمات",
        bot_option_projects: "أرني أفضل أعماله",
        bot_option_hire: "أريد توظيفه!",
        bot_option_consultation: "احصل على استشارة بالذكاء الاصطناعي",
        bot_proactive_prompt: "هل تبحث عن أتمتة ذكية؟ دعني أرشدك.",
        bot_proactive_cta: "لنتحدث",
        bot_back: "رجوع",
        bot_back_to_services: "شاهد خدمات أخرى",
        bot_contact_about_this: "تواصل بخصوص هذا",
        bot_request_this_service: "اطلب هذه الخدمة",
        bot_request_service_title: "اطلب هذه الخدمة",
        bot_request_service_prompt: "اختيار رائع! يرجى تقديم تفاصيلك أدناه للبدء.",
        bot_request_service_name_placeholder: "اسمك",
        bot_request_service_email_placeholder: "بريدك الإلكتروني",
        bot_request_service_phone_placeholder: "رقم هاتفك (اختياري)",
        bot_request_service_message_placeholder: "صف مشروعك أو فكرتك باختصار...",
        bot_request_service_submit: "إرسال الطلب",
        bot_request_success: "شكراً! تم إرسال طلبك. سيتم التواصل معك قريباً.",
        bot_error_key: "البوت غير متاح مؤقتاً (مفتاح API غير موجود).",
        bot_error_api: "عذراً، أواجه مشكلة في الاتصال الآن. يرجى المحاولة مرة أخرى لاحقاً.",
        bot_consultation_title: "استشارة مشروع بالذكاء الاصطناعي",
        bot_consultation_prompt: "صف تحدي عملك أو العملية التي ترغب في أتمتتها. كلما زادت التفاصيل، كان الاقتراح أفضل!",
        bot_consultation_submit: "أنشئ مقترحًا",
        bot_consultation_analyzing: "جاري تحليل مشكلتك...",
        bot_proposal_title: "إليك مقترحك المدعوم بالذكاء الاصطناعي",
        bot_proposal_problem: "تحليل المشكلة",
        bot_proposal_solution: "الحل المقترح",
        bot_proposal_services: "الخدمات الموصى بها",
        bot_discuss_proposal: "ناقش هذا المقترح",
        bot_brainstorm_idea: "دعنا نناقش فكرة",
        bot_brainstorm_prompt: "ما الذي يدور في ذهنك؟ صف رؤيتك أو مشكلتك.",
        bot_brainstorm_submit: "احصل على رأي",
        bot_brainstorm_analyzing: "أفكر...",
        bot_brainstorm_response_title: "إليك فكرة...",
        bot_discuss_idea: "ناقش هذه الفكرة",
    }
};

export const servicesData: Service[] = [
    { icon: 'fas fa-cogs', title: { en: 'n8n Process Automation', ar: 'أتمتة العمليات بـ n8n' }, desc: { en: 'Build custom workflows to connect your apps (Google Sheets, Telegram, Email, Webhooks) and save time and effort.', ar: 'بناء ووركفلوهات مخصصة لربط تطبيقاتك (Google Sheets, Telegram, Email, Webhooks) وتوفير الوقت والجهد.' } },
    { icon: 'fas fa-robot', title: { en: 'Artificial Intelligence Tools', ar: 'أدوات ذكاء اصطناعي' }, desc: { en: 'Create tools for file analysis (PDF, images), customer service, or content generation based on GPT integration.', ar: 'إنشاء أدوات لتحليل الملفات (PDF، صور)، خدمة العملاء، أو توليد المحتوى بالاعتماد على تكامل GPT.' } },
    { icon: 'fas fa-desktop', title: { en: 'SaaS & Custom Interfaces', ar: 'مواقع SaaS وواجهات مخصصة' }, desc: { en: 'Develop customer-facing SaaS sites and design smart, flexible interfaces to control automation systems.', ar: 'تطوير مواقع SaaS موجهة للعملاء وتصميم واجهات ذكية ومرنة للتحكم في أنظمة الأتمتة.' } },
    { icon: 'fa-brands fa-telegram', title: { en: 'Custom Telegram Bots', ar: 'بوتات تليجرام مخصصة' }, desc: { en: 'Program interactive Telegram bots for instant notifications, customer management, or as an entry point to your services.', ar: 'برمجة بوتات تليجرام تفاعلية لأنظمة التنبيهات الفورية، إدارة العملاء، أو كنقطة وصول لخدماتك.' } },
    { icon: 'fas fa-lightbulb', title: { en: 'Technical Consulting', ar: 'استشارات تقنية' }, desc: { en: 'Provide consultations on GPT API integration, choosing the right No-Code tools, and designing automated system architecture.', ar: 'تقديم استشارات في تكامل واجهات GPT، اختيار أدوات No-Code المناسبة، وتصميم بنية الأنظمة المؤتمتة.' } },
];

export const projectsData: Project[] = [
    { title: { en: "Hotel Reservation Management System", ar: "نظام إدارة حجوزات فندقية" }, category: { en: "n8n Workflows", ar: "n8n Workflows" }, description: { en: "An integrated workflow connecting a booking form to Google Sheets, sending instant confirmations via Telegram and Email.", ar: "ووركفلو متكامل يربط بين نموذج حجز، Google Sheets، ويرسل تأكيدات فورية للعميل والإدارة عبر Telegram و Email." }, link: "#", image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600" },
    { title: { en: "NovaLab - Midjourney-like Website", ar: "موقع NovaLab الشبيه بـ Midjourney" }, category: { en: "Websites", ar: "مواقع" }, description: { en: "A prompt-based website for generating artistic images using AI, featuring a modern UI and API integration.", ar: "موقع يعتمد على البرومبتات لتوليد صور فنية باستخدام AI. يتضمن واجهة مستخدم حديثة وتكامل مع واجهات برمجية." }, link: "#", image: "https://images.unsplash.com/photo-1677756119517-756a188d2d94?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600" },
    { title: { en: "Telegram Customer Service Bot", ar: "بوت تليجرام لخدمة العملاء" }, category: { en: "n8n Workflows", ar: "n8n Workflows" }, description: { en: "An intelligent bot that answers common customer inquiries, logs complex requests, and alerts the support team for urgent cases.", ar: "بوت ذكي يرد على استفسارات العملاء الشائعة، يسجل الطلبات المعقدة، ويرسل تنبيهًا لفريق الدعم للحالات الطارئة." }, link: "#", image: "https://images.unsplash.com/photo-1611606063065-ee7946f0787a?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600" },
    { title: { en: "Social Media Analytics SaaS Platform", ar: "منصة SaaS لتحليل السوشيال ميديا" }, category: { en: "Websites", ar: "مواقع" }, description: { en: "A SaaS interface allowing clients to connect accounts to analyze performance, generate reports, and suggest content using AI.", ar: "واجهة SaaS تسمح للعملاء بربط حساباتهم لتحليل الأداء، توليد تقارير، واقتراح محتوى باستخدام الذكاء الاصطناعي." }, link: "#", image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600" },
    { title: { en: "PDF File Analysis Automation", ar: "أتمتة تحليل ملفات PDF" }, category: { en: "n8n Workflows", ar: "n8n Workflows" }, description: { en: "A system that pulls PDF files from an email, uses AI to extract specific information, and saves it to Google Sheets.", ar: "نظام يقوم بسحب ملفات PDF من البريد الإلكتروني، يستخدم AI لاستخلاص معلومات محددة، ثم يحفظها في Google Sheets." }, link: "#", image: "https://images.unsplash.com/photo-1521575107034-e0fa0b594529?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600" }
];

export const ADMIN_EMAIL = 'mabda724@gmail.com'; // Admin user email